### ISSUE TITLE
Not working with latest version of Raku

### ISSUE THREAD

**Issue by JJ** [moritz/Grammar-ErrorReporting#1]
This apparently installs correctly, but does not do a thing:

```
use  Grammar::ErrorReporting;

grammar G does Grammar::ErrorReporting {
    token TOP     {  "*" | "-" | "✅"  \h+ <ingredient> }
    token ingredient      { <quantity> \h* <unit>? }
    token quantity { <:N>+ }
    token unit      { "g" | "tbsp" | "clove" | "tbsps" | "cloves" }
}

say G.parse( "+ food");
```
This simply prints "nil". Did I miss something here?

This also fails:

```
grammar MyTest3 does Grammar::ErrorReporting {

    token TOP     {  ["*" || "-" || "✅"]  \h+ .+ }
}

say MyTest3.parse("* jeez")
```

Any help here?

**Comment by JJ** [comment]
Ping?

**Comment by moritz** [comment]
@JJ sorry for the late response.

`Grammar::ErrorReporting` doesn't magically generate good error messages for you. You have to do one of two things:

* use the `~` parser combinator to match pairs of things.
* call the `error` method from your tokens when you expect something to match, but it doesn't, like

```
token number_with_unit {
    <number>
   [ <unit> || <.error('unit expected')>
}
```
